# Generated by Django 5.2.1 on 2025-05-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.intern')),
            ],
        ),
    ]
